# Generated by Django 5.0.14 on 2025-07-20 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TEXT', '自由記述'), ('CHOICE', '選択式')], default='TEXT', max_length=10, verbose_name='質問タイプ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='自由記述の回答'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='選択肢の文言')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='sample_app.question', verbose_name='対象の質問')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sample_app.choice', verbose_name='選択した回答'),
        ),
    ]
