# Generated by Django 5.0.14 on 2025-07-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Q1',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=100, verbose_name='質問1'),
        ),
    ]
